services:
  postgres:
    image: postgres:16
    container_name: secureapi
    restart: unless-stopped
    environment:
      POSTGRES_DB: secureapi_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: