spring:
  application:
    name: secureapi
  data:
    rest:
      base-path: /api/v1
  datasource:
    url: jdbc:postgresql://localhost:5432/secureapi_db
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect