spring:
  application:
    name: vsc
  data:
    rest:
      base-path: /api/v1
  datasource:
    url: jdbc:postgresql://localhost:5432/vsc_db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect